### PR TITLE
fix: convert Allerigies to RTL

### LINKED ISSUE #54: Convert __tests__/patients/allergies/Allergies.test.tsx

### PR DESCRIPTION
**Pull request by kiranjd**
Fixes #54

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
is this test `FAIL src/__tests__/patients/view/ViewPatient.test.tsx (79.682s)` failing for you locally?

**Comment by kiranjd** [comment]
@JacobMGEvans  No, it’s not. All tests passed on local

**Comment by JacobMGEvans** [comment]
Can you try pulling in recent master updates and then pushing to this branch again 😄

**Comment by kiranjd** [comment]
@JacobMGEvans Tests are passing in all environment now 🎉

**Pull request merged**
